import PPTXGenJS from "pptxgenjs";

const COLORS = {
  primary: "3B82F6",     // Blue
  secondary: "0F172A",   // Slate 900
  accent: "06B6D4",      // Cyan
  text: "1E293B",
  light: "F8FAFC",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "64748B",
  success: "22C55E",
};

export const generatePpt = async (data) => {
  const ppt = new PPTXGenJS();

  // Presentation Settings
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "Ciel-AI";
  ppt.company = "Ciel-AI";
  ppt.title = data?.title || "Presentation";
  ppt.subject = data?.subtitle || "";
  ppt.language = "en-US";

  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
    language: "en-US",
  };

  // Cover Slide
  addCover(ppt, data);

  // Content Slides
  data?.slides?.forEach((slide, index) => {
    addContentSlide(
      ppt,
      slide.title,
      slide.points || [],
      index + 1,
      data.slides.length
    );
  });

  // Thank You Slide
  addThankYouSlide(ppt);

  return ppt;
};



// =========================
// Cover Slide
// =========================
const addCover = (ppt, data) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.primary,
    };

    // Top Accent Bar
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: COLORS.accent,
        },
        line: {
            color: COLORS.accent,
        },
    });

    // Main Title
    slide.addText(data.title || "Untitled Presentation", {
        x: 0.7,
        y: 1.7,
        w: 12,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 36,
        fontFace: "Aptos",
        fit: "shrink",
    });

    // Subtitle
    slide.addText(data.subtitle || "", {
        x: 1,
        y: 2.8,
        w: 11.5,
        h: 0.5,
        align: "center",
        color: "DBEAFE",
        fontSize: 16,
        fontFace: "Aptos",
        fit: "shrink",
    });

    // Footer
    slide.addText("Generated by Ciel-AI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE", // Fixed typo
        fontSize: 10,
        fontFace: "Aptos",
    });
};



// =========================
// Content Slide
// =========================
const addContentSlide = (ppt, title, points = [], page, totalPages) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.light,
    };

    // Slide Title
    slide.addText(title || "Untitled", {
        x: 0.7,
        y: 0.35,
        w: 11,
        h: 0.4,
        fontSize: 24,
        bold: true,
        color: COLORS.secondary,
        fit: "shrink",
    });

    // Horizontal Divider
    slide.addShape(ppt.ShapeType.line, {
        x: 0.5,
        y: 0.9,
        w: 12.3,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1.2,
        },
    });

    // Maximum 6 bullets per slide
    const visiblePoints = points.slice(0, 6);

    visiblePoints.forEach((point, index) => {
        const y = 1.25 + index * 0.72;

        // Background Card
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.58,
            rectRadius: 0.08,
            fill: {
                color: index % 2 === 0 ? "EFF6FF" : "F8FAFC", // Fixed i -> index
            },
            line: {
                color: COLORS.border,
                width: 0.8,
            },
        });

        // Bullet Dot
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.9,
            y: y + 0.22,
            w: 0.08,
            h: 0.08,
            fill: {
                color: COLORS.primary,
            },
            line: {
                color: COLORS.primary,
            },
        });

        // Bullet Text
        slide.addText(point, {
            x: 1.15,
            y: y + 0.08,
            w: 11.2,
            h: 0.35,
            fontSize: 14,
            color: COLORS.text,
            fit: "shrink",
        });
    });

    // Footer (Draw only once)
    slide.addText(`Ciel-AI`, {
        x: 0.6,
        y: 6.9,
        w: 2,
        h: 0.2,
        fontSize: 10,
        color: COLORS.muted,
    });

    slide.addText(`${page}/${totalPages}`, {
        x: 12,
        y: 6.9,
        w: 0.8,
        h: 0.2,
        align: "right",
        fontSize: 10,
        color: COLORS.muted,
    });
};



// =========================
// Thank You Slide
// =========================
const addThankYouSlide = (ppt) => {
    const slide = ppt.addSlide();

    slide.background = {
        color: COLORS.secondary,
    };

    // Main Thank You Text
    slide.addText("Thank You", {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 34,
        bold: true,
    });

    // Subtitle
    slide.addText("Questions?", {
        x: 0,
        y: 3.1,
        w: 13.33,
        h: 0.4,
        align: "center",
        color: "CBD5E1",
        fontSize: 18,
    });

    // Footer
    slide.addText("Generated by Ciel-AI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    });
};