import  PDFDocument  from 'pdfkit';

export const generatePdf = async (data) => {
     return new Promise((resolve, reject) => {
        const doc=  new  PDFDocument({
            size: 'A4',
            margin: 50,
            info:{
                Author: 'Ciel-AI',
                Title: data.title,
                Creator: 'Ciel-AI',
            }
        })

       const chunks=[]
    
    // jab jab data aayega usko chunks ke array daal denge
       doc.on("data",(chunk)=>chunks.push(chunk))
        
    //    ending may chunks ko concat krdenge
       doc.on("end",()=>resolve(Buffer.concat(chunks)))
     
    //    during creation koi error aye to reject krdo 
       doc.on("error",(err)=>reject(err))
    

//   title
       doc
        .fontSize(28)
        .text(data.title,{
            align: 'center',
        })
        .fillColor('#111827')

        // space dega title and subtitle ke beech
        if(data.subtitle){
            doc.moveDown(0.5)
        }

// subtitle
        doc
        .fontSize(16)
        .text(data.subtitle,{
            align: 'center',
        })
        .fillColor('#6B7280')

        doc.moveDown(2)

// section mai data daalenge uske liye loop chalayenge
        
      data?.sections?.forEach(s=>{

      doc
        .fontSize(18)
        .text(s.heading)
        .fillColor('#111827')

         doc.moveDown(0.5)

         s?.points?.forEach(p=>{
            doc
            .fontSize(12)
            .text(" • " + p,{
              lineGap: 5,
            })
            .fillColor('#374151')

        })

       doc.moveDown()
      });
    // footer 
      doc.moveDown()

      doc
       .fontSize(10)
       .text("Generated by Ciel-AI",{
         align: 'center',
       })
       .fillColor('#9CA3AF')

       doc.end()
     })

}